version: "3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - ./src:/code/src
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
      - PORT=3000
    ports:
      - 3000:3000
