name: Cleanup Feature

on:
  delete:
    branches:
      - feature/**
      - hofix/**
      - bug/**
  workflow_dispatch:
    inputs:
      branch_name:
        description: "branch name to do cleanup on"
        required: true

jobs:
  cleanup:
    name: Clean Up Feature
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.2.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.NONPROD_ROLE_ARN }}
          role-duration-seconds: 3600

      - name: Update Kubernetes Configuration for Non-Prod Cluster
        run: |
          aws eks --region us-west-2 update-kubeconfig --name ${{ secrets.NONPROD_CLUSTER_NAME }} --role-arn arn:aws:iam::977624198390:role/KubernetesAdmin

      - name: Set Feature Name From Dispatch Event
        if: "github.event.inputs.branch_name"
        run: |
          RELEASE_NAME=$(echo -n ${{ github.event.inputs.branch_name }} | sed 's/.*\///g' | tr '[:upper:]' '[:lower:]' | cut -d / -f2)
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Set Feature Name From Delete Event
        if: "!github.event.inputs.branch_name"
        run: |
          PROJECT_NAME=$(echo ${{ github.repository }} | cut -d / -f2)
          FEATURE_ID=$(echo -n ${{ github.event.ref }} | sed 's/.*\///g' | tr '[:upper:]' '[:lower:]')
          RELEASE_NAME=${FEATURE_ID}--${PROJECT_NAME}
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV

      - name: Helm Uninstall
        run: |
          echo "RELEASE_NAME:${{ env.RELEASE_NAME }}"
          helm uninstall -n feature ${{ env.RELEASE_NAME }}
